language: python
python:
  - "3.6"
  - "2.7"

install:
  # Including codecov requirements-dev.txt then executing `codecov` is so
  # hacky.  There must be a cleaner way of handling this.
  - pip install tox-travis codecov -r requirements-dev.txt

script:
  - tox

after_success:
  - py.test --cov=./plpacker ./tests/
  - codecov
